apiVersion: v1
kind: ConfigMap
metadata:
  name: server-configmap
data:
  - REDIS_HOST=redis
  - REDIS_PORT=6379
  - PGUSER=postgres
  - PGHOST=postgres
  - PGDATABASE=postgres
  - PGPASSWORD=postgres_password
  - PGPORT=5432
