apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internal-nw-policy
spec:
  podSelector:
    matchExpressions:
      - {key: name, operator: In, values: [postgres-pod, redis-pod]}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: client-pod
    - podSelector:
        matchLabels:
          name: worker-pod
    - podSelector:
        matchLabels:
          name: server-pod
    ports:
      - port: 5432
        protocol: TCP
      - port: 6379
        protocol: TCP
