apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    metadata:
      labels:
        name: nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests: 
              cpu: "30m"
              memory: "28Mi"
            limits:
              cpu: "60m"
              memory: "56Mi"   
  replicas: 1    
  selector:
      matchLabels:
        name: nginx-pod

