apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: server-pod
    spec:     
      containers:
        - name: server
          image: dhruvmewada15/multi-docker_api
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: server-configmap
          resources:
            requests: 
              cpu: "20m"
              memory: "56Mi"
            limits:
              cpu: "40m"
              memory: "128Mi"
  selector:
    matchLabels:
      name: server-pod