apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  template:  
    metadata:
      labels:
        name: worker-pod
    spec:
      containers:
        - name: worker
          image: dhruvmewada15/multi-docker_worker
          envFrom:
            - configMapRef:
                name: worker-configmap
          resources:
            requests: 
              cpu: "30m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod

